.clang-format, .gitattributes, .gitignore, CODE_OF_CONDUCT.md, CONTRIBUTING.md, SECURITY.md, _config.yml, renovate.json
=> build: :construction:

.github/workflows/build.yml
=> build: 🚧 update build.yml

CONTRIBUTING.md
=> docs: 📝 fix contributing.md

logic/TRIAL.md
=> docs: :poop: trial

dependency/proto/Message2Clients.proto, dependency/proto/Message2Server.proto, dependency/proto/MessageType.proto, dependency/proto/Services.proto
- [×] 您的代码是否能够编译通过？
- [×] 您是否检查了目前在 [pull requests](https://github.com/eesast/THUAI8/pulls) 中是否有与你的贡献功能相同的更改？
- [×] 您的贡献是否符合[贡献者代码协议](https://github.com/eesast/THUAI8/blob/dev/CODE_OF_CONDUCT.md)？
- [×] 您的贡献是否符合[开发规则](https://github.com/eesast/THUAI8#%E5%BC%80%E5%8F%91%E8%A7%84%E5%88%99)？  
=> style: proto修改

CAPI/cpp/API/include/structures.h, dependency/proto/Message2Clients.proto, dependency/proto/MessageType.proto
=> 添加structures.h文件；修改proto文件

logic/GameEngine/CollisionChecker.cs, logic/GameEngine/GameEngine.csproj, logic/GameEngine/GameEngineLogging.cs, logic/GameEngine/MoveEngine.cs
=> feat: :sparkles: Logic GameClass Update

logic/Server/RpcServices.cs
=> feat: :sparkles: 添加RpcService

dependency/proto/Message2Clients.proto, logic/Server/CopyInfo.cs
=> feat: :zap: 添加CopyInfo.cs

.github/workflows/build.yml
=> ix:修改build.yml

logic/Preparation/Interface/IOccupation.cs, logic/Preparation/Utility/EnumType.cs
=> feat: :sparkles: GameObjType

CAPI/cpp/API/include/Communication.h, CAPI/cpp/API/include/ConcurrentQueue.hpp, CAPI/cpp/API/include/constants.h, logic/Server/ArgumentOptions.cs, logic/Server/GameServer.cs, logic/Server/HttpSender.cs, logic/Server/PlaybackServer.cs, logic/Server/Server.csproj, logic/Server/ServerBase.cs, logic/Server/ServerLogging.cs
=> 修改GameServer.cs中的GetMessageOfAll函数

logic/Preparation/Interface/ICharacter.cs
=> NameChange

logic/GameClass/GameObj/Areas/Construction.cs, logic/GameClass/GameObj/Character.cs, logic/GameClass/GameObj/Occupations/BaiLongma.cs, logic/GameClass/GameObj/Occupations/HongHaier.cs, logic/GameClass/GameObj/Occupations/JiuLing.cs, logic/GameClass/GameObj/Occupations/Monkid.cs, logic/GameClass/GameObj/Occupations/NiuMowang.cs, logic/GameClass/GameObj/Occupations/OccupationFactory.cs, logic/GameClass/GameObj/Occupations/Pawn.cs, logic/GameClass/GameObj/Occupations/ShaWujing.cs, logic/GameClass/GameObj/Occupations/SunWukong.cs, logic/GameClass/GameObj/Occupations/TangSeng.cs, logic/GameClass/GameObj/Occupations/TieShan.cs, logic/GameClass/GameObj/Occupations/ZhiZhujing.cs, logic/GameClass/GameObj/Occupations/ZhuBajie.cs, logic/Gaming/CharacterManager.cs, logic/Preparation/Interface/ICharacter.cs, logic/Preparation/Utility/GameData.cs
1.Add Occupation; 2.Add Character Manager
1.Add Occupation;
2.Add CharacterManager;
3.Others to complement the above.
=> feat: :sparkles: LogicUpdate

installer/Program.cs
- [ x] 您的代码是否能够编译通过？
- [ x] 您是否检查了目前在 [pull requests](https://github.com/eesast/THUAI8/pulls) 中是否有与你的贡献功能相同的更改？
- [ x] 您的贡献是否符合[贡献者代码协议](https://github.com/eesast/THUAI8/blob/dev/CODE_OF_CONDUCT.md)？
- [ x] 您的贡献是否符合[开发规则](https://github.com/eesast/THUAI8#%E5%BC%80%E5%8F%91%E8%A7%84%E5%88%99)？  
=> fix:installer build error

README.md
=> docs: ✨ update README

logic/GameClass/GameObj/Areas/A_Resource.cs, logic/GameClass/GameObj/Areas/Bush.cs, logic/GameClass/GameObj/Areas/Cage.cs, logic/GameClass/GameObj/Areas/Construction.cs, logic/GameClass/GameObj/Areas/E_Resource.cs, logic/GameClass/GameObj/Areas/NullArea.cs, logic/GameClass/GameObj/Areas/Trap.cs, logic/GameClass/GameObj/Character.cs, logic/Preparation/Utility/GameData.cs
=> feat: :sparkles: Construction Update

logic/.config/dotnet-tools.json, logic/GameClass/GameObj/Areas/A_Resource.cs, logic/GameClass/GameObj/Areas/Bush.cs, logic/GameClass/GameObj/Areas/E_Resource.cs, logic/GameClass/GameObj/Character.cs, logic/GameClass/GameObj/Occupations/BaiLongma.cs, logic/GameClass/GameObj/Occupations/HongHaier.cs, logic/GameClass/GameObj/Occupations/JiuLing.cs, logic/GameClass/GameObj/Occupations/Monkid.cs, logic/GameClass/GameObj/Occupations/NiuMowang.cs, logic/GameClass/GameObj/Occupations/Pawn.cs, logic/GameClass/GameObj/Occupations/ShaWujing.cs, logic/GameClass/GameObj/Occupations/SunWukong.cs, logic/GameClass/GameObj/Occupations/TangSeng.cs, logic/GameClass/GameObj/Occupations/TieShan.cs, logic/GameClass/GameObj/Occupations/ZhiZhujing.cs, logic/GameClass/GameObj/Occupations/ZhuBajie.cs, logic/GameClass/GameObj/Sources/CrazyMan.cs, logic/Preparation/Interface/IA_Recource.cs, logic/Preparation/Utility/EnumType.cs, logic/Preparation/Utility/GameData.cs
=> RecourceUpdate

logic/GameClass/GameObj/Areas/E_Resource.cs, logic/Preparation/Utility/EnumType.cs
=> style: StyleChange

logic/GameClass/GameObj/Areas/Construction.cs, logic/GameClass/GameObj/Character.cs, logic/GameEngine/CollisionChecker.cs, logic/GameEngine/MoveEngine.cs, logic/Gaming/AttackManager.cs, logic/Gaming/CharacterManager.cs
Add AttackManager.Character skillcasting.
=> feat: LogicUpdate

CAPI/cpp/API/include/API.h, CAPI/cpp/API/include/utils.hpp, logic/Server/ArgumentOptions.cs, logic/Server/GameServer.cs
=> fix: :bug: ArgumentOptions.cs和GameServer.cs修正

installer/installer.csproj
=> Revert "chore(deps): update dependency communitytoolkit.maui to v10"

logic/GameClass/GameObj/Base.cs, logic/Gaming/Game.cs, logic/Preparation/Utility/GameData.cs
=> feat: Base complete

interface/AvaloniaUI_debug_interface/debug_interface/Models/MapCell.cs, interface/AvaloniaUI_debug_interface/debug_interface/ViewModels/CharacterViewModel.cs, interface/AvaloniaUI_debug_interface/debug_interface/ViewModels/MapViewModel.cs, interface/AvaloniaUI_debug_interface/debug_interface/ViewModels/ViewModelBase.cs, interface/AvaloniaUI_debug_interface/debug_interface/Views/MainWindow.axaml, interface/AvaloniaUI_debug_interface/debug_interface/Views/MainWindow.axaml.cs, interface/AvaloniaUI_debug_interface/debug_interface/Views/MapView.axaml, interface/AvaloniaUI_debug_interface/debug_interface/Views/MapView.axaml.cs, interface/AvaloniaUI_debug_interface/debug_interface/debug_interface.csproj, logic/proto/Services.proto
- [x ] 您的代码是否能够编译通过？
- [x ] 您是否检查了目前在 [pull requests](https://github.com/eesast/THUAI8/pulls) 中是否有与你的贡献功能相同的更改？
- [x ] 您的贡献是否符合[贡献者代码协议](https://github.com/eesast/THUAI8/blob/dev/CODE_OF_CONDUCT.md)？
- [x ] 您的贡献是否符合[开发规则](https://github.com/eesast/THUAI8#%E5%BC%80%E5%8F%91%E8%A7%84%E5%88%99)？  
=> Debug_interface Prototype

logic/Gaming/Game.cs
=> fix: Shipless

logic/GameClass/GameObj/Areas/Home.cs, logic/GameClass/GameObj/Base.cs, logic/Gaming/A_ResourceManager.cs, logic/Gaming/AttackManager.cs, logic/Gaming/Game.cs, logic/Preparation/Interface/IHome.cs, logic/Preparation/Utility/GameData.cs
=> fix: GameFix

interface/AvaloniaUI_debug_interface/debug_interface/ViewModels/ViewModelBase.cs, interface/AvaloniaUI_debug_interface/debug_interface/debug_interface.csproj
=> Update ViewModel_base logic and Receive from server methods

logic/PlayBack/Playback.csproj
=> fix: :construction: playback.csproj修复

logic/GameClass/GameObj/Base.cs, logic/Gaming/CharacterManager.cs, logic/Gaming/Game.cs, logic/Preparation/Utility/GameData.cs
=> feat: 角色增删修改

dependency/proto/MessageType.proto, dependency/proto/Proto.csproj, dependency/proto/Proto.sln, logic/PlayBack/Playback.csproj, logic/Preparation/Preparation.csproj, logic/logic.sln
=> fix: :construction: fix "TRAP"

logic/GameClass/GameClass.csproj, logic/GameEngine/GameEngine.csproj, logic/Gaming/Gaming.csproj, logic/Preparation/Utility/Transformation.cs, logic/Server/Server.csproj
=> fix: 3.30.0

CAPI/cpp/proto/MessageType.pb.cc, logic/Gaming/ActionManager.cs, logic/Gaming/Game.cs
=> style: fix style

logic/Gaming/AttackManager.cs, logic/Gaming/EquipmentManager.cs, logic/Gaming/Game.cs
=> Game.Update

installer/Data/ConfigFileData.cs, installer/Model/Logger.cs, interface/AvaloniaUI_debug_interface/debug_interface/App.axaml, interface/AvaloniaUI_debug_interface/debug_interface/App.axaml.cs, interface/AvaloniaUI_debug_interface/debug_interface/Models/MapCell.cs, interface/AvaloniaUI_debug_interface/debug_interface/ViewModels/CharacterViewModel.cs, interface/AvaloniaUI_debug_interface/debug_interface/ViewModels/MainWindowViewModel.cs, interface/AvaloniaUI_debug_interface/debug_interface/ViewModels/MapViewModel.cs, interface/AvaloniaUI_debug_interface/debug_interface/Views/MainWindow.axaml, interface/AvaloniaUI_debug_interface/debug_interface/Views/MapView.axaml, interface/AvaloniaUI_debug_interface/debug_interface/Views/MapView.axaml.cs, interface/AvaloniaUI_debug_interface/debug_interface/debug_interface.csproj
=> Debug_interface added character sign in map

installer/installer.csproj, installer/installer.sln
=> fix:修改release

dependency/proto/Message2Server.proto, dependency/proto/Proto.csproj, dependency/proto/Services.proto, interface/Unity/interface-live/Assets/Scripts/Define/MessageType.cs, logic/Server/PlaybackServer.cs, logic/Server/RpcServices.cs
=> 修复了RpcServices.cs中的bug

logic/GameClass/GameObj/Areas/A_Resource.cs, logic/GameClass/GameObj/Areas/A_Resource/Factory.cs, logic/GameClass/GameObj/Areas/Barriers.cs, logic/GameClass/GameObj/Areas/Bush.cs, logic/GameClass/GameObj/Areas/Cage.cs, logic/GameClass/GameObj/Areas/Construction.cs, logic/GameClass/GameObj/Areas/E_Resource.cs, logic/GameClass/GameObj/Areas/Home.cs, logic/GameClass/GameObj/Areas/NullArea.cs, logic/GameClass/GameObj/Areas/OutOfBoundBlock.cs, logic/GameClass/GameObj/Areas/Trap.cs, logic/GameClass/GameObj/Character.cs, logic/GameClass/GameObj/Map/Map.cs, logic/Gaming/A_ResourceManager.cs, logic/Gaming/ActionManager.cs, logic/Gaming/AttackManager.cs, logic/Gaming/Game.cs, logic/Gaming/SkillCastManager.cs, logic/Preparation/Utility/EnumType.cs, logic/Preparation/Utility/GameData.cs, logic/Preparation/Utility/Transformation.cs, logic/Server/CopyInfo.cs, logic/Server/GameServer.cs
=> style: 命名更改

logic/Server/RpcServices.cs
=> fix: :bug: bug修改

CAPI/cpp/API/src/Communication.cpp, CAPI/python/Communication.py
=> feat: :sparkles: communication.py初步

CAPI/cpp/API/include/structures.h, CAPI/cpp/API/src/logic.cpp, dependency/proto/Message2Clients.proto, dependency/proto/MessageType.proto, logic/Server/CopyInfo.cs
=> refactor: :zap: 对接Character

logic/ClientTest/Program.cs, logic/GameClass/GameObj/Character.cs, logic/Gaming/Game.cs
=> fix: CharacterHPInit

logic/GameClass/GameObj/Character.cs, logic/Gaming/CharacterManager.cs
=> fix: Chraracter补充InvisibleTime

map-generator/JavaScript/assets/js/map.js, map-generator/JavaScript/index.html
=> Fix bug on MapGenerator

logic/Gaming/A_ResourceManager.cs, logic/Preparation/Utility/GameData.cs
=> feat: 加成资源3/7分钟升级

dependency/proto/Proto.csproj, installer/Data/ConfigFileData.cs, interface/AvaloniaUI_debug_interface/debug_interface/Controls/MapHelper.cs, interface/AvaloniaUI_debug_interface/debug_interface/Models/MapCell.cs, interface/AvaloniaUI_debug_interface/debug_interface/ViewModels/MainWindowViewModel.cs, interface/AvaloniaUI_debug_interface/debug_interface/ViewModels/MapViewModel.cs, interface/AvaloniaUI_debug_interface/debug_interface/ViewModels/ViewModelBase.cs, interface/AvaloniaUI_debug_interface/debug_interface/Views/MainWindow.axaml, interface/AvaloniaUI_debug_interface/debug_interface/Views/MapView.axaml.cs, interface/AvaloniaUI_debug_interface/debug_interface/debug_interface.csproj, interface/AvaloniaUI_debug_interface/debug_interface/debug_interface.sln, log.txt, logic/PlayBack/MessageReader.cs
- [ x] 您的代码是否能够编译通过？
- [ x] 您是否检查了目前在 [pull requests](https://github.com/eesast/THUAI8/pulls) 中是否有与你的贡献功能相同的更改？
- [ x] 您的贡献是否符合[贡献者代码协议](https://github.com/eesast/THUAI8/blob/dev/CODE_OF_CONDUCT.md)？
- [ x] 您的贡献是否符合[开发规则](https://github.com/eesast/THUAI8#%E5%BC%80%E5%8F%91%E8%A7%84%E5%88%99)？  
=> Debug_interface - Update display of other Mapcells

docs/THUAI8_API接口文档.md
=> docs: 📝 增加更完善的API接口文档

.github/workflows/docker.yml
=> chore:docker

installer/ViewModel/DebugViewModel.cs
=> fix:installer

CAPI/cpp/API/src/logic.cpp
=> fix: :bug: 关于log日志不同队伍分别写入不同文件的改正

logic/Gaming/CharacterManager.cs
=> fix: :bug: 这次应该不会扣血了把

CAPI/cpp/API/include/API.h, CAPI/cpp/API/include/Communication.h, CAPI/cpp/API/include/logic.h, CAPI/cpp/API/src/AI.cpp, CAPI/cpp/API/src/API.cpp, CAPI/cpp/API/src/Communication.cpp, CAPI/cpp/API/src/DebugAPI.cpp, CAPI/cpp/API/src/logic.cpp, run_API.cmd
=> fix: :bug: 移动问题修复

.gitignore
=> .gitignore忽略log日志

CAPI/cpp/API/include/API.h, CAPI/cpp/API/src/AI.cpp, CAPI/cpp/API/src/API.cpp, CAPI/cpp/API/src/DebugAPI.cpp
=> fix: :bug: Move bug更改

CAPI/cpp/API/src/API.cpp
=> fix: :bug: API注释修改

CAPI/python/PyAPI/AI.py, CAPI/python/PyAPI/API.py, CAPI/python/PyAPI/Communication.py, CAPI/python/PyAPI/DebugAPI.py, CAPI/python/PyAPI/Interface.py, CAPI/python/PyAPI/logic.py, docs/CAPI.md
=> fix: :bug: API修改（python部分）

logic/Gaming/Game.cs
=> fix: fix bug

CAPI/cpp/API/include/API.h, CAPI/cpp/API/include/Communication.h, CAPI/cpp/API/include/logic.h, CAPI/cpp/API/include/utils.hpp, CAPI/cpp/API/src/API.cpp, CAPI/cpp/API/src/Communication.cpp, CAPI/cpp/API/src/DebugAPI.cpp
=> fix: :bug: 关于Common_Attack和Skill_Attack参数的简化与修改

CAPI/cpp/API/include/structures.h, CAPI/cpp/CMakeLists.txt
=> fix: ⚡ fix CMakeLists.txt

CAPI/cpp/API/src/logic.cpp
=> fix: :bug: 关于log输出角色bug的修复

CAPI/cpp/API/src/AI.cpp, CAPI/cpp/API/src/API.cpp, CAPI/cpp/API/src/DebugAPI.cpp
=> fix: :bug: 运动方向bug修改

.gitignore, dependency/shell/run.sh, logic/Server/ArgumentOptions.cs
=> fix: run.sh

CAPI/python/PyAPI/AI.py, CAPI/python/PyAPI/API.py, CAPI/python/PyAPI/DebugAPI.py, CAPI/python/PyAPI/logic.py, CAPI/python/PyAPI/structures.py
=> fix: :bug: TeamAPI fix

CAPI/cpp/API/include/API.h, CAPI/cpp/API/include/logic.h, CAPI/cpp/API/include/structures.h, CAPI/cpp/API/src/API.cpp, CAPI/cpp/API/src/DebugAPI.cpp, CAPI/cpp/API/src/logic.cpp, CAPI/python/PyAPI/AI.py, CAPI/python/PyAPI/API.py, CAPI/python/PyAPI/Communication.py, CAPI/python/PyAPI/DebugAPI.py, CAPI/python/PyAPI/Interface.py, CAPI/python/PyAPI/logic.py, CAPI/python/PyAPI/structures.py, docs/CAPI.md, docs/THUAI8_API接口文档.md
=> GetEconomyResourceState接口修改为返回int

logic/Gaming/ActionManager.cs, logic/Gaming/Game.cs
=> fix: 建筑修建的问题

CAPI/cpp/API/include/API.h, CAPI/cpp/API/include/logic.h, CAPI/cpp/API/include/structures.h, CAPI/cpp/API/src/API.cpp, CAPI/cpp/API/src/DebugAPI.cpp, CAPI/cpp/API/src/logic.cpp, CAPI/python/PyAPI/AI.py, CAPI/python/PyAPI/API.py, CAPI/python/PyAPI/Communication.py, CAPI/python/PyAPI/DebugAPI.py, CAPI/python/PyAPI/Interface.py, CAPI/python/PyAPI/logic.py, CAPI/python/PyAPI/structures.py, docs/CAPI.md, docs/THUAI8_API接口文档.md
=> Revert "GetEconomyResourceState接口修改为返回int"

docs/THUAI8_API接口文档.md
=> fix: :bug: 两种attack在API文档中的修正

CAPI/cpp/CMakeLists.txt, dependency/shell/compile.sh, dependency/shell/run.sh
=> feat: ⚡ update run.sh

CAPI/cpp/API/include/API.h, CAPI/cpp/API/include/Communication.h, CAPI/cpp/API/include/logic.h, CAPI/cpp/API/include/structures.h, CAPI/cpp/API/include/utils.hpp, CAPI/cpp/API/src/API.cpp, CAPI/cpp/API/src/Communication.cpp, CAPI/cpp/API/src/DebugAPI.cpp, CAPI/cpp/API/src/logic.cpp, CAPI/cpp/API/src/main.cpp, CAPI/cpp/proto/Message2Clients.pb.cc, CAPI/cpp/proto/Message2Clients.pb.h, CAPI/cpp/proto/Message2Clients.proto, dependency/proto/Message2Clients.proto, dependency/proto/Message2Server.proto, dependency/proto/MessageType.proto, dependency/proto/Services.proto, docs/THUAI8_API接口文档.md
=> fix: 🐛 关于EconomyResource、AdditionResource、Construction信息获取的改进，另外还添加了AttackConstruction、AttackAdditionResource函数，但尚未完成

CAPI/python/PyAPI/API.py, CAPI/python/PyAPI/DebugAPI.py, CAPI/python/PyAPI/Interface.py, CAPI/python/PyAPI/logic.py, CAPI/python/PyAPI/structures.py, docs/THUAI8_API接口文档_for_python.md
=> 更改GetEconomyResourceState等接口信息

CAPI/cpp/API/include/API.h, CAPI/cpp/API/include/Communication.h, CAPI/cpp/API/include/logic.h, CAPI/cpp/API/include/structures.h, CAPI/cpp/API/include/utils.hpp, CAPI/cpp/API/src/API.cpp, CAPI/cpp/API/src/Communication.cpp, CAPI/cpp/API/src/DebugAPI.cpp, CAPI/cpp/API/src/logic.cpp, CAPI/cpp/API/src/main.cpp, CAPI/cpp/proto/Message2Clients.pb.cc, CAPI/cpp/proto/Message2Clients.pb.h, CAPI/cpp/proto/Message2Clients.proto, dependency/proto/Message2Clients.proto, dependency/proto/Message2Server.proto, dependency/proto/MessageType.proto, dependency/proto/Services.proto, docs/THUAI8_API接口文档.md
=> Revert "fix: 🐛 关于EconomyResource、AdditionResource、Construction信息获取的改进，另外还添加了AttackConstruction、AttackAdditionResource函数，但尚未完成"

dependency/proto/Proto.csproj, interface/AvaloniaUI_debug_interface/debug_interface/debug_interface.csproj, logic/GameClass/GameClass.csproj, logic/GameEngine/GameEngine.csproj, logic/Gaming/Gaming.csproj, logic/PlayBack/Playback.csproj, logic/Server/Server.csproj
=> Revert "chore(deps): update dependency grpc.tools to 2.72.0"

CAPI/cpp/API/include/API.h, CAPI/cpp/API/include/Communication.h, CAPI/cpp/API/include/logic.h, CAPI/cpp/API/include/structures.h, CAPI/cpp/API/include/utils.hpp, CAPI/cpp/API/src/API.cpp, CAPI/cpp/API/src/Communication.cpp, CAPI/cpp/API/src/DebugAPI.cpp, CAPI/cpp/API/src/logic.cpp, CAPI/cpp/proto/Message2Server.pb.cc, CAPI/cpp/proto/Message2Server.pb.h, CAPI/cpp/proto/Services.grpc.pb.cc, CAPI/cpp/proto/Services.grpc.pb.h, CAPI/cpp/proto/Services.pb.cc, dependency/proto/Message2Server.proto, dependency/proto/Services.proto
=> fix: :bug: 资源获取、攻击建筑与资源、建造陷阱的修改

CAPI/cpp/API/include/API.h, CAPI/cpp/API/include/logic.h, CAPI/cpp/API/src/API.cpp, CAPI/cpp/API/src/DebugAPI.cpp, CAPI/cpp/API/src/logic.cpp, CAPI/cpp/proto/Message2Server.pb.cc, CAPI/cpp/proto/Message2Server.pb.h, dependency/proto/Message2Server.proto, docs/THUAI8_API接口文档.md
=> fix: :bug: 接口文档更新

CAPI/python/PyAPI/AI.py, CAPI/python/PyAPI/API.py, CAPI/python/PyAPI/Communication.py, CAPI/python/PyAPI/DebugAPI.py, CAPI/python/PyAPI/Interface.py, CAPI/python/PyAPI/logic.py, CAPI/python/PyAPI/utils.py, docs/THUAI8_API接口文档_for_python.md, log.txt, logic/Server/RpcServices.cs
=> feat: :sparkles: 添加AttackAdditionResource、ConstructTrap接口

CAPI/cpp/API/include/API.h, CAPI/cpp/API/src/API.cpp, CAPI/cpp/API/src/DebugAPI.cpp, docs/THUAI8_API接口文档.md
=> fix: :bug: Produce参数修改以及接口文档更新

CAPI/python/PyAPI/API.py
=> fix: :bug: api.py修改

CAPI/python/PyAPI/API.py, logic/Server/GameServer.cs
=> fix: 🐛 api.py修改

logic/Server/CopyInfo.cs
=> fix: :bug: copyinfo对齐

logic/Preparation/Utility/GameData.cs
=> NeedCopy Fix

logic/GameClass/GameObj/Areas/Construction.cs, logic/GameClass/GameObj/Character.cs, logic/Gaming/ActionManager.cs, logic/Preparation/Utility/GameData.cs
=> fix bug on construction & equipment

logic/GameClass/GameObj/Areas/A_Resource.cs
=> fix bug on a_resource

interface/AvaloniaUI_debug_interface/debug_interface/Controls/MapHelper.cs, interface/AvaloniaUI_debug_interface/debug_interface/Models/MapCell.cs, interface/AvaloniaUI_debug_interface/debug_interface/ViewModels/MainWindowViewModel.cs, interface/AvaloniaUI_debug_interface/debug_interface/ViewModels/MapViewModel.cs, interface/AvaloniaUI_debug_interface/debug_interface/Views/MainWindow.axaml, interface/AvaloniaUI_debug_interface/debug_interface/Views/MapView.axaml.cs
=> Debug_interface - Update cell text, character hp，farmcolor

CAPI/cpp/API/include/API.h, CAPI/cpp/API/include/logic.h, CAPI/cpp/API/include/structures.h, CAPI/cpp/API/include/utils.hpp, CAPI/cpp/API/src/API.cpp, CAPI/cpp/API/src/DebugAPI.cpp, CAPI/cpp/API/src/logic.cpp, CAPI/cpp/proto/Message2Clients.pb.cc, CAPI/cpp/proto/Message2Clients.pb.h, dependency/proto/Message2Clients.proto, docs/THUAI8_API接口文档.md
=> fix: 🐛 添加GetTrapMessage函数

CAPI/cpp/API/src/logic.cpp, CAPI/python/PyAPI/API.py, CAPI/python/PyAPI/DebugAPI.py, CAPI/python/PyAPI/Interface.py, CAPI/python/PyAPI/logic.py, CAPI/python/PyAPI/structures.py, docs/THUAI8_API接口文档_for_python.md, logic/Server/CopyInfo.cs
=> 添加GetTrapState接口

interface/AvaloniaUI_debug_interface/debug_interface/Controls/MapHelper.cs, interface/AvaloniaUI_debug_interface/debug_interface/ViewModels/MainWindowViewModel.cs, interface/AvaloniaUI_debug_interface/debug_interface/ViewModels/MapViewModel.cs, interface/AvaloniaUI_debug_interface/debug_interface/Views/MainWindow.axaml
=> Debug_interface - Fixed HealthBar

installer/ViewModel/DebugViewModel.cs
=> fix loglevel

interface/AvaloniaUI_debug_interface/debug_interface/ViewModels/MainWindowViewModel.cs, interface/AvaloniaUI_debug_interface/debug_interface/ViewModels/ViewModelBase.cs, interface/AvaloniaUI_debug_interface/debug_interface/Views/MainWindow.axaml
=> Debug Interface - healthBar Fix 2.0

logic/Gaming/SkillCastManager.cs
=> Add skill casting log

logic/Gaming/AttackManager.cs, logic/Gaming/CharacterManager.cs, logic/Gaming/Game.cs, logic/Preparation/Utility/Value/SafeValue/MyTimer.cs, logic/Preparation/Utility/ValueInterface/IMyTimer.cs
=> fix bug on A_Resource & game end

logic/Gaming/AttackManager.cs, logic/Gaming/Game.cs
=> Fix bug on attack addition resource

logic/Gaming/SkillCastManager.cs
=> Update skill-casting manager

CAPI/cpp/API/include/utils.hpp
=> merge to main

installer/Data/ConfigFileData.cs, interface/AvaloniaUI_debug_interface/debug_interface/ViewModels/MainWindowViewModel.cs, interface/AvaloniaUI_debug_interface/debug_interface/ViewModels/ViewModelBase.cs
=> Debug_interface - Playback LAST TRY

logic/Gaming/A_ResourceManager.cs, logic/Gaming/CharacterManager.cs
=> update a_resource attack

CAPI/python/PyAPI/logic.py
=> fix: :bug: logic.py隐身判断修改

CAPI/cpp/API/include/utils.hpp
=> fix: :bug: attackconstruction传参修改

logic/GameClass/GameObj/Areas/Cage.cs, logic/GameClass/GameObj/Areas/Hole.cs, logic/GameClass/GameObj/Areas/TrapBase.cs, logic/GameClass/GameObj/Map/Map.cs, logic/Gaming/ActionManager.cs, logic/Gaming/AttackManager.cs, logic/Gaming/SkillCastManager.cs
=> fix trap bug & add thread for attack
